services:
  - type: web
    name: members-only
    runtime: node
    plan: free
    region: virginia
    repo: https://github.com/benaiah324/members-only
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: MEMBERSHIP_PASSCODE
        value: clubhouse2026
      - key: ADMIN_PASSCODE
        value: admin-secret
      - key: DATABASE_URL
        fromDatabase:
          name: Benaiah_Postgres
          property: connectionString

databases:
  - name: Benaiah_Postgres
    plan: free
    region: virginia
